apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 640537815570.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-repo
  newName: 640537815570.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-repo
  newTag: 587b3d9d
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
