apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 876630244803.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-repo
  newName: 876630244803.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-repo
  newTag: a987237d
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
